# Search
search: 
  enable: true
  service: hexo


# friends link
links:
  - name: My Github
    url: https://github.com/PngWnA
  - name: CTF Server managed by me
    url: https://soviet.kr
  - name: Astronomical Picture Of the Day
    url: https://apod.nasa.gov
  - name: Best Program ever
    url: https://kitribob.kr

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: About
    slug: about
    url: /about
  - name: Archives
    slug: archives
    url: /archives

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/PngWnA
- slug: facebook
  url: https://facebook.com/msviolinest
- slug: rss
  url: /atom.xml
